### ISSUE TITLE
Does this work with CNN?

### ISSUE THREAD

**Issue by imagine5am** [vanHavel/bp-mll-tensorflow#3]
I am running  the code here: https://colab.research.google.com/drive/1Da16UW8PudKFfGs756vClp0G_IpiJsGA

But after some steps the loss is NaN.
Is there something I am doing wrong?

**Comment by vanHavel** [comment]
Just a wild guess, could it be that you have data points that have no genres or all genres as labels?

Otherwise, could you please provide a minimal example where the loss returns NaN?

**Comment by imagine5am** [comment]
I figured it out. There may be some datapoints with all genres. 
Its working now.
Thanks for the support.
